CREATE TABLE IF NOT EXISTS tracker(id serial PRIMARY KEY,name VARCHAR (200),description TEXT,create_date TIMESTAMP WITHOUT TIME ZONE,update_date TIMESTAMP WITHOUT TIME ZONE);
CREATE TABLE IF NOT EXISTS comments(id serial PRIMARY KEY,message TEXT,create_date TIMESTAMP WITHOUT TIME ZONE,id_item INTEGER REFERENCES tracker(id));
